### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by elona-dup**
Added CAD2Sketch in the CAD Generation category

### CODE REVIEW

**Comment by bertjiazheng** [comment]
Hi @elona-dup, Thanks for your contribution. This paper deals with an inverse problem of CAD sketch generation and may not be categorized into the CAD generation part.

**Comment by elona-dup** [comment]
I agree, I was a bit unsure where it should be put.
Do you think it would be more suited in the CAD Recognition section? Or should there be a new section?

**Comment by bertjiazheng** [comment]
This paper can be categorized into rendering techniques. I would like to let this repository focuses on modeling, reconstruction, etc. Would you mind not adding this paper to the repo?

**Comment by elona-dup** [comment]
That makes sense. I will close the pull request then.

**Comment by bertjiazheng** [comment]
Thanks for your contributions and understanding.

**Pull request closed without merging**
